# Arc list 

A list contains arcs of a graph
<img src="network.PNG" />

In [80]:
graph= [(1,2),(2,4),(4,6),(3,2),(2,5),(3,1),(4,5),(6,5)]
print(graph)

[(1, 2), (2, 4), (4, 6), (3, 2), (2, 5), (3, 1), (4, 5), (6, 5)]


# Doing Adjacency matrix

<img src="dgraph.png" />

In [71]:
import csv
import numpy as np


def constructAdjMat(fname):
    with open(fname, newline='') as csvfile:
        d=csv.reader(csvfile)
        n=0
        list=[]
        for row in d:
            n=max(n,int(row[0]),int(row[1]))
            list.append(row)
        matrix=np.zeros((n,n),dtype=bool)
        print(n)
        print(list)
        for row in list:
            i,j = int(row[0])-1,int(row[1])-1
            matrix[i,j]=True
    return matrix
    #print(matrix*1)
            

        
matrix=constructAdjMat('data.csv')
print(matrix)
print("\n")
print(matrix*1)

6
[['1', '2'], ['2', '4'], ['3', '1'], ['3', '2'], ['4', '5'], ['4', '6'], ['6', '5']]
[[False  True False False False False]
 [False False False  True False False]
 [ True  True False False False False]
 [False False False False  True  True]
 [False False False False False False]
 [False False False False  True False]]


[[0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [1 1 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]]


In [69]:
#node degree from adj matrix
def node_degree(n, adjMatrix):
    indg=np.sum(adjMatrix[:,n])
    outdg=np.sum(adjMatrix[n,:])
    return indg, outdg
    
print(node_degree(0,matrix))

(1, 1)


# Adjacency list

In [79]:
import csv
import numpy as np

def constructAdjList(fname):
    matrix=1
    with open(fname, newline='') as csvfile:
        d=csv.reader(csvfile)
        n=0
        list=[]
        for row in d:
            n=max(n,int(row[0]),int(row[1]))
            list.append(row)
        matrix=[[] for i in range(n)]
        print(matrix[0])
        
        for row in list:
            i,j = int(row[0])-1,int(row[1])
            matrix[i].append(j)
    return matrix
        
            

        
adjList=constructAdjList('data.csv')
print(adjList)

[]
[[2], [4], [1, 2], [5, 6], [], [5]]


In [126]:
#from matrix to adjacency list
def matList(m):
    n=len(m)
    ls=[[] for i in range(n)]
    for i in range(n):
        ls[i]=np.nonzero(m[i,:])
        ls[i]=[item.tolist() for item in ls[i]]
        #print(ls[i])
        #ls[i]=ls[i].tolist()
    
    return ls

print(matList(matrix))

[[[1]], [[3]], [[0, 1]], [[4, 5]], [[]], [[4]]]


In [127]:
#from adjacency list to matrix
def adjTomat(aList):
    n=len(aList)
    m=np.zeros((n,n),dtype=bool)
    for i in range(len(aList)):
        j=aList[i]
        for indx in j:
            m[i,indx-1]=True
    
    return m

print(adjTomat(adjList))

[[False  True False False False False]
 [False False False  True False False]
 [ True  True False False False False]
 [False False False False  True  True]
 [False False False False False False]
 [False False False False  True False]]


In [121]:
#check tree
def checkTree(m):
    n=len(m)
    numArcs=m.sum()
    if numArcs == n-1:
        return True
    return False

print(checkTree(matrix))

False
[[False  True  True False False]
 [False False False False False]
 [False False False  True  True]
 [False False False False False]
 [False False False False False]]
second Tree:  True


# check if it's tree
<img src="tree.png" />

In [125]:
# if tree

m2=np.zeros((5,5), dtype=bool)
m2[0,1],m2[0,2]=True, True
m2[2,3], m2[2,4]=True, True
print(m2)
print("\nsecond Tree: ",checkTree(m2))

[[False  True  True False False]
 [False False False False False]
 [False False False  True  True]
 [False False False False False]
 [False False False False False]]

second Tree:  True
