# What's o(n) analysis?

# Tree
<img src="btree.png"/>
<img src="move.png" />

# Search algorithm?
<img src="alg.png"/>

# Breadth First
<img src="gl2.png" />

In [47]:
adjList=[[1,2],[2,3],[],[4,2],[2,3]]
print(adjList)

[1, 2]


In [37]:
def admissable(i,marked,AdjL):
    for node in AdjL[i]:
        if not marked[node]:
            return True, node
    
    return False,0

In [43]:
import numpy as np

def bfs(startN,AdjL):
    # Initialization
    n=len(AdjL) # O(1)
    pred=np.zeros((n)) # O(n)
    #pred=[]*n
    pred[0]=-1
    order=np.zeros((n))  # O(n)
    marked=np.zeros((n),dtype=bool)  # O(n)
    next=1  # O(1)
    order[startN]=next  # O(1)
    marked[startN]=True  # O(1)
    LIST=[]
    LIST.append(startN)  # O(1)... 
    
    # Main search part
    # deal with it like a queue
    # o(n)
    while LIST: # while not empty
        print("Ls: ",LIST)
        i=LIST[0]
        found,j=admissable(i,marked,AdjL) #o(m)
        print(found," ",j)
        if found:
            marked[j]=True
            pred[j]=i
            next+=1
            order[j]=next
            LIST.append(j) # O(1)
        else:
            #delete first one
            LIST.pop(0)
        
    # Returning 
    return pred,order,marked


pred, order, marked =bfs(0,adjList)
print(pred,"\n",order,'\n',marked)

Ls:  [0]
True   1
Ls:  [0, 1]
True   2
Ls:  [0, 1, 2]
False   0
Ls:  [1, 2]
True   3
Ls:  [1, 2, 3]
False   0
Ls:  [2, 3]
False   0
Ls:  [3]
True   4
Ls:  [3, 4]
False   0
Ls:  [4]
False   0
[-1.  0.  0.  1.  3.] 
 [1. 2. 3. 4. 5.] 
 [ True  True  True  True  True]


# Depth First

In [46]:
def dfs(startN,AdjL):
    # Initialization
    n=len(AdjL) # O(1)
    pred=np.zeros((n)) # O(n)
    #pred=[]*n
    pred[0]=-1
    order=np.zeros((n))  # O(n)
    marked=np.zeros((n),dtype=bool)  # O(n)
    next=1  # O(1)
    order[startN]=next  # O(1)
    marked[startN]=True  # O(1)
    LIST=[]
    LIST.append(startN)  # O(1)... 
    
    # Main search part
    # deal with it like a stack
    while LIST: # while not empty
        print("Ls: ",LIST)
        i=LIST[-1]
        found,j=admissable(i,marked,AdjL)
        print(found," ",j)
        if found:
            marked[j]=True
            pred[j]=i
            next+=1
            order[j]=next
            LIST.append(j) # O(1)
        else:
            #delete last one
            LIST.pop()
        
    # Returning 
    return pred,order,marked


pred, order, marked =dfs(0,adjList)
print(pred,"\n",order,'\n',marked)

Ls:  [0]
True   1
Ls:  [0, 1]
True   2
Ls:  [0, 1, 2]
False   0
Ls:  [0, 1]
True   3
Ls:  [0, 1, 3]
True   4
Ls:  [0, 1, 3, 4]
False   0
Ls:  [0, 1, 3]
False   0
Ls:  [0, 1]
False   0
Ls:  [0]
False   0
[-1.  0.  1.  1.  3.] 
 [1. 2. 3. 4. 5.] 
 [ True  True  True  True  True]


In [44]:
n=[1,2,3]
print(n[-1])

3
